### ISSUE TITLE
Surface capability scanning (Capslock) in the API

### ISSUE THREAD

**Issue by jamietanna** [google/deps.dev#100]
Via https://blog.deps.dev/capslock/ this is an awesome set of data!

I couldn't spot it surfaced in https://docs.deps.dev/api/v3alpha/#getversion - would it be possible to get it added at some point? 🤞🏽 Thanks!

**Comment by jessmcclintock** [comment]
Thanks for asking! Capslock capability results are now available in the API. The documentation is here: https://docs.deps.dev/api/v3alpha/#getcapabilities
