### ISSUE TITLE
Package not found statistically 

### ISSUE THREAD

**Issue by noy-duany** [google/deps.dev#103]
Hi, I'm using deps.dev api to query dependencies of packages.
Sometimes I get Package not found for a package that indeed exist, and afterwards I get the real response.

Why is this happening?

**Comment by sarnesjo-google** [comment]
Hi @noy-duany! It's hard to diagnose without a specific example, but in general, this can happen for packages and versions that were recently released. The time it takes for deps.dev to pick up new releases varies between ecosystems, but is typically measured in minutes or hours, with the worst-case outliers measured in weeks. After that, it takes additional time to compute dependencies for it, typically around 12 hours.
