### ISSUE TITLE
Bug: No data received via API

### ISSUE THREAD

**Issue by bardenstein** [google/deps.dev#110]
**Goal**
I'm trying to use the deps.dev API to look up dependencies.

https://deps.dev/maven/org.springframework.boot%3Aspring-boot-starter exists in the UI.

**Problem**
curl 'https://api.deps.dev/v3/query?versionKey.system=MAVEN&versionKey.name=spring-boot-starter'

no results match query%

Why can't I find spring-boot-starter via the API?

**Comment by sarnesjo-google** [comment]
Documentation for the API is available at [docs.deps.dev](https://docs.deps.dev/api/v3/).

To use the Query endpoint, you need to fully specify either `versionKey` or `hash` or both. Note that `versionKey` has 3 fields, and you're omitting `version` (and you also have a typo in `name`). Example:

    curl 'https://api.deps.dev/v3/query?versionKey.system=MAVEN&versionKey.name=org.springframework.boot%3Aspring-boot-starter&versionKey.version=3.3.5'

Please note that the main purpose of the Query endpoint is to support lookup by hash. If you have a version identifier, it's easier to use the GetVersion endpoint instead.
