### ISSUE TITLE
Ability to expose if dependencies are direct or indirect

### ISSUE THREAD

**Issue by lumjjb** [google/deps.dev#12]
Is it possible to also expose if dependencies are direct or indirect, we are trying to build up the graph of dependencies and encode the structure within [GUAC](https://github.com/guacsec/guac)

**Comment by adg** [comment]
The information is already there in the [`GetDependencies`](https://docs.deps.dev/api/v3alpha/#getdependencies) response. If the `edges` list contains an entry with `fromNode` `0`, then its `toNode` points to a direct dependency in the `nodes` list.

Does that make sense? Perhaps we should provide an example and/or call this out directly in the docs.

**Comment by pxp928** [comment]
@adg Could you provide an example to better explain this?

**Comment by adg** [comment]
@pxp928 sure. For example, the npm package react has three transitive dependencies:

```
$ curl -s https://api.deps.dev/v3alpha/systems/npm/packages/react/versions/17.0.0:dependencies | jq
{
  "nodes": [
    {
      "versionKey": {
        "system": "NPM",
        "name": "react",
        "version": "17.0.0"
      },
      "bundled": false,
      "errors": []
    },
    {
      "versionKey": {
        "system": "NPM",
        "name": "js-tokens",
        "version": "4.0.0"
      },
      "bundled": false,
      "errors": []
    },
    {
      "versionKey": {
        "system": "NPM",
        "name": "loose-envify",
        "version": "1.4.0"
      },
      "bundled": false,
      "errors": []
    },
    {
      "versionKey": {
        "system": "NPM",
        "name": "object-assign",
        "version": "4.1.1"
      },
      "bundled": false,
      "errors": []
    }
  ],
  "edges": [
    {
      "fromNode": 0,
      "toNode": 2,
      "requirement": "^1.1.0"
    },
    {
      "fromNode": 0,
      "toNode": 3,
      "requirement": "^4.1.1"
    },
    {
      "fromNode": 2,
      "toNode": 1,
      "requirement": "^3.0.0 || ^4.0.0"
    }
  ],
  "error": ""
}
```

In the `edges` list, the `fromNode` is the index in `nodes` of the package that declared the dependency, and the `toNode` is the index in `nodes` of the dependent package. Since the first entry in `nodes` is always the root package, any edge with a `fromNode` of `0` is a direct dependency.

Here's an example that uses [`jq`](https://stedolan.github.io/jq/manual/) to print the from/to edges as package names, and whether the dependency is direct or indirect:

```
$ curl -s https://api.deps.dev/v3alpha/systems/npm/packages/react/versions/17.0.0:dependencies | jq -j '
        # Gather the names of each node.
        [.nodes[].versionKey.name] as $names |

        # For each edge, print the names of the from/to nodes, and whether the
        # "to" node depends on the root (it is a "direct" dependency).
        .edges[] | (
                $names[.fromNode], " -> ", $names[.toNode], " ",
                if .fromNode == 0 then
                        "(direct)"
                else
                        "(indirect)"
                end, "\n"
        )
'
react -> loose-envify (direct)
react -> object-assign (direct)
loose-envify -> js-tokens (indirect)
```

Let me know if this is helpful to you. (I can understand if the `jq` stuff is confusing - it is a bit of an esoteric language).

We'll also look at adding an example Go program to this repo that demonstrates better how to work with `GetDependencies` responses, and consider whether there should be a different dependencies API endpoint if the current one is too cumbersome.

**Comment by sarnesjo** [comment]
The requirement on the edge is declared by the "from" node.

As for the original question about marking direct/indirect dependencies, what @adg says is exactly right: a client can determine this by looking for all the edges from node 0. With that said, it seems like a simple and worthwhile improvement to make this explicit in the API. I'll work on that.

**Comment by sarnesjo** [comment]
Nodes in dependency graphs now have a `relation` field marking them as direct or indirect dependencies (or "self" for the node representing the package version that the dependency graph is for).

As an example, here's what the nodes in the dependency graph for react 18.1.0 look like in the HTTP API:

```
$ curl -s 'https://api.deps.dev/v3alpha/systems/npm/packages/react/versions/18.1.0:dependencies' | jq '.nodes'
[
  {
    "versionKey": {
      "system": "NPM",
      "name": "react",
      "version": "18.1.0"
    },
    "bundled": false,
    "relation": "SELF",
    "errors": []
  },
  {
    "versionKey": {
      "system": "NPM",
      "name": "js-tokens",
      "version": "4.0.0"
    },
    "bundled": false,
    "relation": "INDIRECT",
    "errors": []
  },
  {
    "versionKey": {
      "system": "NPM",
      "name": "loose-envify",
      "version": "1.4.0"
    },
    "bundled": false,
    "relation": "DIRECT",
    "errors": []
  }
]
```

**Comment by lumjjb** [comment]
Note to self for this thread, the assumption on "So if i have 0->1->2, would querying the API for the package for "1" or "2" result in more information?", the answer is "yes", since a different tree is returned based on the root node provided (based on discussions). Just documenting here to correct myself in the issue.
