### ISSUE TITLE
Clarify license for data from deps.dev API

### ISSUE THREAD

**Issue by garethr** [google/deps.dev#15]
The documentation mentions the [terms](https://github.com/google/deps.dev#terms) under which the API can be used, but links to the generic Google API terms https://developers.google.com/terms. I don't see a specific reference to the license under which the data is made available? Could this be made explicit? A suitable creative commons license would be ideal (with attribution if preferred), but any explicit license would be better than none.

**Comment by behnazh-w** [comment]
We need a similar clarification to use the API in project [Macaron](https://github.com/oracle/macaron).

**Comment by sarnesjo** [comment]
Sorry about the delay on this. We now have clearer data licensing: CC-BY 4.0 for the data that deps.dev generates, in addition to the data licensing terms of our data sources, which are now listed all in one place. This applies to the deps.dev [API](https://docs.deps.dev/api/v3alpha/#data) as well as the [BigQuery dataset](https://docs.deps.dev/bigquery/v1/#data).
