### ISSUE TITLE
Getting release / publish date for versions 

### ISSUE THREAD

**Issue by vasumv** [google/deps.dev#17]
Is there any way of fetching the release / publish date for versions? Seems like it's listed on the website as the publish date, but I don't see a way of getting it through the API or the BigQuery dataset.

Thanks!

**Comment by tyler-french** [comment]
I am also very interested in this feature. Currently, one needs to connect with NPM, Maven, and pkg.go.dev directly in order to get release date on these versions. 

Version age is very important, and this seems to be an important gap between the deps.dev web UI and the API.

**Comment by vasumv** [comment]
Sorry for the additional bump - any updates on whether this feature might be coming or ~how long it might take?

**Comment by adg** [comment]
An update: this is a work in progress and we hope to have version publication times (for the systems that support them) available in the API within the next week.

**Comment by adg** [comment]
There is now a `publishedAt` field in the [`GetPackage` response](https://docs.deps.dev/api/v3alpha/#getpackage), [`GetVersion` response](https://docs.deps.dev/api/v3alpha/#getversion), and [`Query` response](https://docs.deps.dev/api/v3alpha/#query).

@vasumv yes, we have also added a `UpstreamPublishedAt` field to [`PackageVersions` table](https://docs.deps.dev/bigquery/v1/#packageversions), which should be populated in the next snapshot.
