### ISSUE TITLE
Honor retracted versions

### ISSUE THREAD

**Issue by liggitt** [google/deps.dev#18]
https://deps.dev/go/k8s.io%2Fclient-go is incorrectly identifying a four-year-old version (v12.0.0+incompatible) as the default version.

However, that version is [retracted](https://github.com/kubernetes/client-go/blob/v1.5.2/go.mod#L6-L45) and v0.27.1 is the latest / default version (and has much healthier status - https://deps.dev/go/k8s.io%2Fclient-go/v0.27.1)

Please honor the `retract` directive properly to avoid misleading users of the site with incorrect default version info - https://go.dev/ref/mod#go-mod-file-retract

**Comment by adg** [comment]
Thanks for the report. Since retractions are declared by the go.mod of the latest version, and our system mistakenly treats v12.0.0 as the latest version, the retraction isn't being observed. I have a fix in the pipe that should rectify this.

**Comment by adg** [comment]
The fix has rolled out and the correct latest version is now being displayed. Thanks again for the report.

(Next step is to de-prioritize retracted versions in the versions list, and also in API responses.)
