### ISSUE TITLE
show available "Security Advisories" and "Licenses" when "Failed to fetch dependencies."

### ISSUE THREAD

**Issue by benken-parasoft** [google/deps.dev#19]
This is a request to enhance the package information pages on https://deps.dev/ when dependency information is not available.

For example:
https://deps.dev/maven/org.apache.activemq%3Aactivemq-broker/5.18.1

The "Dependencies" box shows "Failed to fetch dependencies" which is true. This currently returns a 404:
https://api.deps.dev/v3alpha/systems/maven/packages/org.apache.activemq%3Aactivemq-broker/versions/5.18.1:dependencies

However, what is problematic or unexpected is that both "Security Advisories" and "Licenses" also show "Failed to fetch dependencies" even though that information is available:
https://api.deps.dev/v3alpha/systems/maven/packages/org.apache.activemq%3Aactivemq-broker/versions/5.18.1
```
{
  "versionKey": {
    "system": "MAVEN",
    "name": "org.apache.activemq:activemq-broker",
    "version": "5.18.1"
  },
  "isDefault": true,
  "licenses": [
    "Apache-2.0"
  ],
  "advisoryKeys": [],
  "links": [
    {
      "label": "SOURCE_REPO",
      "url": "https://github.com/apache/activemq"
    },
    {
      "label": "ISSUE_TRACKER",
      "url": "https://issues.apache.org/jira/browse/AMQ"
    },
    {
      "label": "HOMEPAGE",
      "url": "http://activemq.apache.org"
    }
  ]
}
```

As a user, I would still expect to see the license and any security advisories.

**Comment by cuixq** [comment]
@benken-parasoft thank you for the feedback! this is definitely an improvement that we could do. I will let you know once these information is available on deps.dev.

**Comment by adg** [comment]
An update: a fix for this is in the pipeline and should be available on deps.dev soon.

**Comment by cuixq** [comment]
@benken-parasoft the fix is now available on deps.dev.
