### ISSUE TITLE
Missing links for Go package versions

### ISSUE THREAD

**Issue by pxp928** [google/deps.dev#2]
Is there an issue where the API is not properly querying for GO packages?

For example, I am querying this [go package](https://deps.dev/go/github.com%2FPuerkitoBio%2Fpurell/v1.1.1) via the API and I am not getting `field Links []*pb.Link` back from the `*pb.Version` even though it shows it on deps.dev. 

my `pb.VersionKey` is as follows:
```
	versionReq := &pb.GetVersionRequest{
		VersionKey: &pb.VersionKey{
			System:  System_GO (1),
			Name:    "github.com/puerkitobio/purell",
			Version: "v1.1.1",
		},
	}
```

Querying with the same `pb.VersionKey` for the dependencies works but specifically, I am looking to get the link that contains the "SOURCE_REPO" such that I can use that in `GetProjectRequest` to find the scorecard information.

Querying `pkg:pypi/wheel@0.37.1` via the same method works without an issue.

**Comment by adg** [comment]
Thanks for the report.

The data is there (obviously, since we surface it on deps.dev), we just need to surface it properly in the api responses. Will take a look at this.

**Comment by adg** [comment]
`SOURCE_REPO` links should now be included for most (if not all) Go modules, eg:

```
$ curl https://api.deps.dev/v3alpha/systems/go/packages/github.com%2fpuerkitobio%2fpurell/versions/v1.1.1 | jq
{
  "versionKey": {
    "system": "GO",
    "name": "github.com/PuerkitoBio/purell",
    "version": "v1.1.1"
  },
  "isDefault": false,
  "licenses": [
    "BSD-3-Clause"
  ],
  "advisoryKeys": [],
  "links": [
    {
      "label": "SOURCE_REPO",
      "url": "https://github.com/puerkitobio/purell"
    }
  ]
}
```
