### ISSUE TITLE
Python wrapper around the API

### ISSUE THREAD

**Issue by eclipseo** [google/deps.dev#27]
I wrote a Python wrapper around the API called pydepsdev:

 - https://github.com/eclipseo/pydepsdev
 - https://pypi.org/project/pydepsdev/

Licensed as ASL 2.0 like this repo.

I am just a hobbyist so the quality of the code may be dubious, but it could be of use for others.

I intend to use it during Fedora Go packaging, to compute the licenses of all the dependencies of a binary, which we were not able to easily do before.

**Comment by sarnesjo** [comment]
Neat! If you'd like, please create a PR adding a link to your repo in the **Third party tools and integrations** section of the README.
