### ISSUE TITLE
Querying for dependent packages

### ISSUE THREAD

**Issue by vasumv** [google/deps.dev#3]
Would it be possible to query the dependents of a particular package using the API? The info is available on the deps.dev website (e.g. [https://deps.dev/maven/org.apache.logging.log4j%3Alog4j-core/2.20.0/dependents](https://deps.dev/maven/org.apache.logging.log4j%3Alog4j-core/2.20.0/dependents) ). Currently, it seems like the API has support for fetching the dependency graph, but I'm wondering if the dependent data could also be exposed.

Thanks!

**Comment by sarnesjo** [comment]
Popular packages can have hundreds of thousands of dependents ([example](https://deps.dev/npm/lodash/4.17.21/dependents)), which makes them tricky to serve via the API, at least as currently designed. This is also why we only show a precomputed sample of the dependents on the deps.dev website.

You can however use our BigQuery dataset to compute all dependents of a given package version, with a query similar to this one: https://docs.deps.dev/bigquery/v1/#dependent-count

**Comment by adg** [comment]
@agmond 

1. Do a [`GetDependencies`](https://docs.deps.dev/api/v3alpha/#getdependencies) call for the package version you're interested in.
2. For each node in the response, do a [`GetVersion`](https://docs.deps.dev/api/v3alpha/#getversion) call, and inspect the `advisoryKeys` field in the returned objects.

**Comment by agmond** [comment]
Thanks, @adg.
It would be helpful to have this ability with a single API call, because for a package with thousands of (sub-)dependencies one should call the `GetVersion` API thousands of times

**Comment by sarnesjo** [comment]
Hi @agmond! I filed #16 to discuss including advisories (and other things, such as licenses), and will close this issue, as the original question about dependents has been answered.
