### ISSUE TITLE
New API endpoint to get specific dependent versions 

### ISSUE THREAD

**Issue by noqcks** [google/deps.dev#31]
Hello! I would love to have a deps.dev API endpoint for the following scenario.

Scenario: I'm using the package [xmlbuilder v4.1.0](https://deps.dev/npm/xmlbuilder/4.1.0). It has the indirect dependency [lodash v3.10.1](https://deps.dev/npm/lodash/3.10.1) which contains the vulnerability [GHSA-29mw-wpgm-hmr9](https://deps.dev/advisory/osv/GHSA-29mw-wpgm-hmr9).

Given I know that the vulnerability is fixed in lodash v4.17.21 because of the advisory, I'd like to search the dependents of lodash for all versions of xmlbuilder to see which version of xmlbuilder is using v4.17.21 so that I can upgrade to that version.

The equivalent bigquery would look something like this

```
SELECT DISTINCT
    Dependent.System AS DependentSystem,
    Dependent.Name AS DependentName,
    Dependent.Version AS DependentVersion,
    MinimumDepth,
    DependentIsHighestReleaseWithResolution
FROM `bigquery-public-data.deps_dev_v1.Dependents`
WHERE Name = 'lodash' 
AND Version = '4.17.21' 
AND Dependent.Name = 'xmlbuilder';
```

Would this be feasible?

**Comment by adg** [comment]
I think this use case would be served by this feature request: https://github.com/google/deps.dev/issues/11#issuecomment-1567617376

Does that sound right to you?

**Comment by noqcks** [comment]
Yep, I think we can close this in favor of that issue.
