### ISSUE TITLE
Querying 'deps.dev' using Fetch API

### ISSUE THREAD

**Issue by rzarviv** [google/deps.dev#35]
It's probably more of a question than an issue, but I'm trying to query the API using Fetch API (i.e. from a javascript code) and I encounter a CORS problem.

For example, I'm trying to run this code: 
`const response = await fetch('https://api.deps.dev/v3alpha/systems/npm/packages/%40colors%2Fcolors')` but I got blocked by the browser.

Is there any header/parameter i'm missing here, or there's any other way in which I can query the API from a client application?

Thanks!

**Comment by adg** [comment]
Thanks for the report. A little work on our end is required to make this work. Will update this bug when it's done.

**Comment by sarnesjo** [comment]
Hi @rzarviv! api.deps.dev should be correctly configured for CORS now. Thanks for the report, and please let us know if you encounter any further issues.

**Comment by rzarviv** [comment]
Thanks @sarnesjo, I'll check that.
