### ISSUE TITLE
missing NuGet package `Microsoft.Azure.Storage.Common`

### ISSUE THREAD

**Issue by noqcks** [google/deps.dev#41]
I noticed that `Microsoft.Azure.Storage.Common` was not indexed. https://www.nuget.org/packages/Microsoft.Azure.Storage.Common/

Wondering if there's a particular reason. Thank you!

**Comment by josieang** [comment]
Thanks for reporting this issue!

I've just looked into it. I think the key here is that it's a deprecated package.

When we launched NuGet we decided not to make deprecated packages searchable for two reasons:
*  nuget.org doesn't typically make deprecated packages searchable in their UI. (eg. [searching xcst.web doesn't show a result for xcst.web](https://www.nuget.org/packages?q=xcst.web ), xcst.web is only accessible via a [direct link](https://www.nuget.org/packages/xcst.web).
* deprecated packages make up about 40% of all package versions that we ingest for NuGet. It's not unprecedented, but it's very high compared to the other ecosystems we support.

However, I noticed that unlike xcst.web, the package you mentioned _is searchable on nuget.org_. See [microsoft.azure.storage.common](https://www.nuget.org/packages?q=Microsoft.Azure.Storage.Common). I've reached out to nuget.org and asked them what criteria they use allow deprecated packages to appear in their search to see whether we should do something similar.

That's a long answer. But the bottom line is that while we've decided not to make deprecated packages searchable, they should still be available in:
* our API,
*  BigQuery dataset (make sure to lowercase/canonicalise the name),
* and while not searchable, available via a direct link. In this case https://deps.dev/nuget/microsoft.azure.storage.common.
