### ISSUE TITLE
Missing Golang Versions

### ISSUE THREAD

**Issue by fingeromer** [google/deps.dev#43]
Examples: 

[`uniseg` latest version is `v0.4.4`](https://pkg.go.dev/github.com/rivo/uniseg?tab=versions) (since Feb 2023): 
But in deps.dev this version [doesn't exist ](https://deps.dev/go/github.com%2Frivo%2Funiseg/v0.4.3/versions)

Same with `runewidth@v0.0.14`: 
https://pkg.go.dev/github.com/mattn/go-runewidth?tab=versions
https://deps.dev/go/github.com%2Fmattn%2Fgo-runewidth

And more

**Comment by adg** [comment]
Thanks for the report. I can confirm the issues with those two modules, and they should be now fixed. There's some ongoing work in progress to make sure we don't have further inconsistencies.

**Comment by adg** [comment]
We believe the underlying issue that caused these versions to be missing has been fixed. Please let us know if you find more inconsistencies in our data.
