### ISSUE TITLE
API to access dependents for a specific version

### ISSUE THREAD

**Issue by R3x** [google/deps.dev#45]
Hello, 

I am trying to do some analysis on package usage especially with PyPI packages. I know there are APIs that are present for viewing the dependencies of packages - but is there a way to parse the dependents of a package given the version via the api?

**Comment by sarnesjo** [comment]
We currently don't serve dependents via the API, as popular package versions can have 100k+ dependents. You can however access them using our [BigQuery dataset](https://docs.deps.dev/bigquery/v1/#dependents).
