### ISSUE TITLE
Wrong response type: string should be int

### ISSUE THREAD

**Issue by edoardottt** [google/deps.dev#47]
Hi google team.

@zaibon just opened an issue in my repo (https://github.com/edoardottt/depsdev/issues/51) pointing out that the fields `lineCount`  and `lineCoverCount` are strings now, but **they should be integers** following the docs (https://docs.deps.dev/api/v3alpha/#getproject).

Try this:
```console
curl "https://api.deps.dev/v3alpha/projects/github.com%2Fklauspost%2Fcompress" | grep -i linecount
```

```
...
"ossFuzz":{"lineCount":"20711","lineCoverCount":"12156",
...
```

What are your thoughts on this? Will you change the docs or the APIs? 

thanks

**Comment by sarnesjo** [comment]
Thanks for reporting this. It is indeed a bug in the generated documentation for our the API.

A bit of technical detail: Our API can be accessed via gRPC or as JSON-over-HTTP, with the latter being implemented in terms of the former. The canonical service definition can be found in [api.proto](https://github.com/google/deps.dev/blob/main/api/v3alpha/api.proto), which uses `int64` for these fields, which is [encoded as `string` in JSON](https://protobuf.dev/programming-guides/proto3/#json) to avoid precision loss when used from JavaScript, whose `number` type [only supports integers up to 2^53-1](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER).

As a short-term fix, we have updated our documentation generator and regenerated the documentation to correctly describe these fields as `string`. In a future version of the API, we will change their type to `int32`/`number`, but for now, we want to avoid breaking existing clients.

**Comment by edoardottt** [comment]
Thank you so much for the answer @sarnesjo.

So I have to assume *ALL* number types in that docs mean string? (e.g. *edges[].fromNode: number* in *GetDependencies*)
