### ISSUE TITLE
what so much data is stored

### ISSUE THREAD

**Issue by zhangzhenyu2** [google/deps.dev#57]
I'd like to know what so much data is stored in, not myql.

**Comment by sarnesjo** [comment]
We use a few different storage systems for different use cases, but the main ones are [GCS](https://cloud.google.com/storage) and [Spanner](https://cloud.google.com/spanner), along with [BigQuery](https://cloud.google.com/bigquery) for our public dataset.

**Comment by zhangzhenyu2** [comment]
thanks
