### ISSUE TITLE
LLM Dependency chatbot

### ISSUE THREAD

**Issue by Mohannadcse** [google/deps.dev#60]
Hi Deps.dev team,

This work is very interesting and useful. To boost its benefits, I've recently developed and implemented an LLM dependency chatbot for Python packages based on the cool DepsDev API. 
For a given Python package, the dependency graph will be constructed as a knowledge graph in Neo4j. I implemented several tools to automate the generation of Cypher queries to read/write from and to the knowledge graph. 

Here you can find the details of [my LinkedIn post](https://www.linkedin.com/posts/engmohannad_curious-about-seeing-a-retrieval-augmented-activity-7156654487548428289-gI9s?utm_source=share&utm_medium=member_desktop).

```
Curious about seeing a Retrieval-Augmented Generation (RAG) app on top of Knowledge Graphs in the software supply chain domain, I'm excited to share our Python Dependency Chatbot. 
Thanks to [Langroid](https://www.linkedin.com/company/langroid/) framework for facilitating the development of this application by enabling multi-agent and supporting neo4j graph database.

The chatbot in action, a gif recording shows how to use the app: 
https://shorturl.at/nN578

More details: 
https://shorturl.at/lMO13

Try it in this Colab Notebook:
https://shorturl.at/oAO07 

Or run it as a script:
https://shorturl.at/CDKR7

What's next:
- Adding more agents to handle vulnerabilities, version conflicts, and licensing.
- Considering other languages.
```

Mohannad 
http://mohannadcse.netlify.app

**Comment by adg** [comment]
Very cool! Thanks for sharing.
