### ISSUE TITLE
Add input examples / OpenAPI spec

### ISSUE THREAD

**Issue by edoardottt** [google/deps.dev#63]
It would be cool to have a list of input that provides the full responses for the API.  
This could be a test for the clients using the API to check if everything is working correctly.  
So non only something like `@colors/colors`

Just to be clear, an OpenAPI specification could help, by a lot.

**Comment by sarnesjo** [comment]
I'm not quite sure what your feature request is. :)

There are already examples of requests in the [API documentation](https://docs.deps.dev/api/v3alpha/), as well as more fleshed-out client examples in the [examples](https://github.com/google/deps.dev/tree/main/examples) directory of this repo. We can't include expected responses, as those change over time. For instance, GetPackage includes additional versions as they're released, GetVersion includes advisories as they're published, etc.

For discussion around an OpenAPI definition, please see #5.

**Comment by edoardottt** [comment]
understood, thanks for the answer
