### ISSUE TITLE
how to get the checksum information or some type of hash value of the package through the API

### ISSUE THREAD

**Issue by zhangzhenyu2** [google/deps.dev#66]
how to get the checksum information or some type of hash value of the package through the API

**Comment by sarnesjo** [comment]
That is not currently possible using the API. You can do the reverse, look up a package version by hash, using the [Query](https://docs.deps.dev/api/v3alpha/#query) endpoint.

Alternatively, you can use our [BigQuery dataset](https://docs.deps.dev/bigquery/v1/) to look up hashes associated with a package version.
