### ISSUE TITLE
license ids do not always correspond to the official SPDX list

### ISSUE THREAD

**Issue by kenwark** [google/deps.dev#73]
I noticed that querying the Maven package `org.javassist:javassist@3.20.0-GA` returns a result where one of the licenses is LGPL-2.1. However, the [official SPDX license list](https://spdx.org/licenses/) does not include this as an id. SPDX has LGPL-2.1-only and LGPL-2.1-or-later.

**Comment by sarnesjo** [comment]
Hi @kenwark! LGPL-2.1 is a deprecated license, and is listed here: https://spdx.org/licenses/#deprecated

**Comment by kenwark** [comment]
Thanks for the reply @sarnesjo. It seems the deprecated LGPL-2.1 and LGPL-2.1+ should map to LGPL-2.1-only and LGPL-2.1-or-later respectively. That is fine.
