### ISSUE TITLE
Commercial use of deps.dev 

### ISSUE THREAD

**Issue by sriumcp** [google/deps.dev#75]
Is it permissible to use the API service definitions in this repo, as part of a commercial product or a service, in order to query deps.dev?

***

The code in this repo (deps.dev service definitions) are licensed under Apache v2.0.

However, the deps.dev API itself is subject to Google API Terms of Service as noted in the README.

***

I am unsure what the implications of the two together are for commercial use of deps.dev. 

Thanks in advance for the clarification.

**Comment by adg** [comment]
The license and ToS of [deps.dev](http://deps.dev/)'s client code and API are the same as for most other Google services (eg, Google Cloud Platform).
