### ISSUE TITLE
Compatibility v3 - v3alpha

### ISSUE THREAD

**Issue by edoardottt** [google/deps.dev#76]
I'm the author of [depsdev client](https://github.com/edoardottt/depsdev) and I'm trying to give people the opportunity to choose between 3 and v3alpha. I'm trying to understand how you treat the development of these two versions. Is v3alpha an "extension" of v3 API? 
1. v3alpha just add new response items wrt v3?
2. There could be input items for v3alpha not allowed for v3? 
3. There could exist an item in the responses that is added in v3 and not in v3alpha?

Based on your responsed I have to understand if I have to treat v3alpha as an extension of v3 for future features or as 2 separate branches of the same project. Thanks

**Comment by adg** [comment]
v3alpha provides no stability guarantees and so users of v3alpha should be very aware that what they depend on is not stable.

IMO, you should maintain the v3 and v3alpha clients as separate packages. They are separate API endpoints (and proto files), after all.

**Comment by edoardottt** [comment]
thank you so much @adg
