### ISSUE TITLE
Missing Go package github.com/docker/cli

### ISSUE THREAD

**Issue by shahar-h** [google/deps.dev#84]
Go package [github.com/docker/cli](https://pkg.go.dev/github.com/docker/cli) is missing:

<img width="820" alt="image" src="https://github.com/google/deps.dev/assets/16555289/ef8d8dd9-27a6-4309-b25a-505393357d23">

**Comment by sarnesjo-google** [comment]
Hi @shahar-h! Thanks for reporting this issue, which turned out to be related to #98. The missing module is now available in deps.dev, although it'll again take a few hours for derived data to be computed.
