### ISSUE TITLE
How to choose the default version of a package

### ISSUE THREAD

**Issue by zhangzhenyu2** [google/deps.dev#91]
How to choose the default version of a package? Is it based on the release time of the package? The latest release time package is the default version？

**Comment by sarnesjo** [comment]
deps.dev chooses the default version of a package using ecosystem-specific logic which is intended to match the behavior of the canonical, upstream tools (e.g. `npm`, `mvn`, etc).

Taking npm as an example, if the package has a [dist-tag called `latest`](https://docs.npmjs.com/cli/v10/commands/npm-dist-tag#purpose), the version it points to is chosen. If not, the greatest version by semver order, ignoring versions with prerelease or build tags, is chosen. Release time is not used.
