### ISSUE TITLE
Missing github.com/distribution/reference Go package

### ISSUE THREAD

**Issue by shahar-h** [google/deps.dev#98]
<img width="576" alt="image" src="https://github.com/google/deps.dev/assets/16555289/73819049-32bf-414d-8b24-a023471bb6ca">

**Comment by sarnesjo-google** [comment]
Hi @shahar-h! Thanks for reporting this issue. The missing module is now available in deps.dev, although it'll take a few hours for derived data, such as dependencies, to be computed.
